### ISSUE TITLE
variants: consider indexing more fields

### ISSUE THREAD

**Issue by buchanae** [bmeg/grip#105]
This query takes far too long:
`list(O.query().V().where(aql.eq("_label", "Variant")).where(aql.eq("chromosome", "1")).where(aql.eq("start", 27100988)).limit(10))`

```
kellrott [12:05 PM]
700,000 variants on chromosome 1 and neither the chromsome or start fields are indexed. so its scanning them all
```

It's probably worth indexing chromosome, start, end, referenceBases, and alternateBases.

**Comment by adamstruck** [comment]
This is specific to the BMEG graph. Closing since it is not directly related to GRIP.
