### ISSUE TITLE
arachne load vs arachne mongoload 

### ISSUE THREAD

**Issue by bwalsh** [bmeg/grip#121]
Ran into performance issue.  Unclear if difference in performance was expected :   

* `arachne load g2p --vertex /data/mc3.Variant.Vertex.json `
   * approx 125 documents / sec
   * default badger 

* `arachne mongoload  g2p --vertex /data/mc3.Variant.Vertex.json  --host mongodb:27017`
  * approx 8000 documents / sec

**Comment by kellrott** [comment]
Yes, mongoload skips the regular drivers and dumps data directly into mongo without validating it.

**Comment by adamstruck** [comment]
Update:  mongoload appears to be slow now as well due to recent changes...

**Comment by kellrott** [comment]
Probably something to do with batch size in loader. With #138 it has a higher default and is configurable. Please check against performance against PR

**Comment by kellrott** [comment]
Can we close this?
