### ISSUE TITLE
Gripql python 3.5 incompatibility

### ISSUE THREAD

**Issue by pagreene** [bmeg/grip#158]
The python package (installed via `pip install "git+https://github.com/bmeg/grip.git#subdirectory=gripql/python"`) does not check for bytes-type responses, and by failing to decode the json string, causes a TypeError whenever reading from the database: https://github.com/pagreene/grip/blob/4d2053a1ef050342f062fbc2738d27de53ef2b70/gripql/python/gripql/query.py#L275

Python 3.6 simply ignores the distinction between bytes and strings.

**Comment by adamstruck** [comment]
Fixed in #159
