### ISSUE TITLE
Queries that are used to return non-empty results are returning empty

### ISSUE THREAD

**Issue by metincansiper** [bmeg/grip#216]
Hi there,
We use this api for [CwC BMEGAgent](https://github.com/metincansiper/BMEGAgent/tree/bioagents_interface). Some of the agent test methods are failing. That is because of that some queries on BMEG api are returning empty results though they are used to return non-empty results. 

[find_mutation_frequency()](https://github.com/metincansiper/BMEGAgent/blob/master/bmeg_agent/bmeg_agent.py#L97) is one of such methods. One of the api queries that is used to return some results but now returns empty is [this one](https://github.com/metincansiper/BMEGAgent/blob/master/bmeg_agent/bmeg_agent.py#L102). It is supposed to get the gene id for the last vertice that has the given gene symbol (I guess so, I did not implement that but looks like that. Also the gene symbol is TP53 in our case). The other one is [here](https://github.com/metincansiper/BMEGAgent/blob/master/bmeg_agent/bmeg_agent.py#L107). I do not know about the other queries that is done after in this method since the method returns ``0`` after the second query returns empty.

I initially thought that this may be related to some api changes but then I realized that our agent connects to the graph ``bmeg_rc1_2`` (https://github.com/metincansiper/BMEGAgent/blob/master/bmeg_agent/bmeg_agent.py#L91) and some gene id is being returned when I try to connect ``bmeg_rc2``  (like in example of documents) instead.

My main questions considering these points are:

- Are there any api changes that happened lately and would potentially cause any of these?
- Why the queries may be returning empty results for ``bmeg_rc1_2`` while they are not used to be?
- Do you think there would be a bug or misbehavior in api or is there something that I should be updating in our agent?

``find_drugs_for_mutation_dataset()`` method of the same file is also used to pass the tests but now it fails. I believe that the reason would be similar.

Thanks!

**Comment by adamstruck** [comment]
It appears that the data for `bmeg_rc1_2` was never loaded on that server. Try using `bmeg_rc1_3`. It shouldn't contain any breaking changes. 

If you would prefer to use the most up-to-date data you can use `bmeg_rc2`; however, the schema changed a fair amount. Most notably all of the edges were renamed.  For example [this](https://github.com/metincansiper/BMEGAgent/blob/master/bmeg_agent/bmeg_agent.py#L107-L108) query would change to: 
```
q = self.O.query().V(proj_id).out("cases").out("samples").out("aliquots").has(
            gripql.eq("gdc_attributes.sample_type", "Primary Tumor")).as_("sample").out("somatic_callsets").select("sample")
```

**Comment by metincansiper** [comment]
@adamstruck Thanks! Most of the things are working for me after your responses here and offline.

I am closing the issue.
