### ISSUE TITLE
Schema info not found (404 errors)

### ISSUE THREAD

**Issue by ehinderer** [bmeg/grip#268]
I'm trying to view the BMEG schema diagram but I'm running into what seem like HTTP 404 errors. From the code described [here](https://bmeg.io/analyze/examples#Graph%20Info):

> import networkx as nx
> import matplotlib.pyplot as plt
> import gripql
> from networkx.drawing.nx_agraph import graphviz_layout
> conn = gripql.Connection("https://bmeg.io/api", credential_file="bmeg_credentials.json")
> print(conn.listGraphs())
[]

> schema = conn.getSchema("rc5")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/gripql/connection.py", line 52, in getSchema
    raise_for_status(response)
  File "/usr/local/lib/python3.9/site-packages/gripql/util.py", line 162, in raise_for_status
    raise requests.HTTPError(http_error_msg, response=response)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: 'https://bmeg.io/api/v1/graph/rc5/schema'esponse: {"code":5,"message":"graph rc5: not found","details":[]}

**Comment by kellrott** [comment]
Apologies, the backend mongo database shutdown and needed to be restarted. The system should be available now.

**Comment by ehinderer** [comment]
Sorry for the late response. I will give this another shot soon, along with my other posted issue. Are you the appropriate contact person to reach out to regarding questions on the BMEG initiative. My team at Tufts CTSI are interested in learning more about it (the incorporation of pathway commons in particular) and may want to contribute if it's appropriate.

**Comment by kellrott** [comment]
Yes, I lead the project. 

GRIP is our query engine. It's designed to be a general purpose graph query engine that can plug into external data resources. BMEG is a specific graph build, largely concentrating on cancer related genomic, drug response and knowledge base resources. It is built from the scripts found in https://github.com/bmeg/bmeg-etl

You can read about some of the scientific goals at https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7049249/

**Comment by ehinderer** [comment]
Thanks! I haven't seen this article, I will give it a read. My team may reach out in the near future. Is there a preferred line of communication?

**Comment by kellrott** [comment]
Email works: ellrott at ohsu dot edu
