### ISSUE TITLE
Concurrency control

### ISSUE THREAD

**Issue by buchanae** [bmeg/grip#39]
Concurrent writes are a fact of life. Most databases deal with this in some way. Arachne shouldn't be an exception.

Consider exploring the style of MVCC that Elasticsearch (and many others) employ, where the database will compare a version string before committing the update.

**Comment by buchanae** [comment]
Also applies to fast writes; I think I'm getting unexpected, inconsistent results writing to arachne backend by mongo

**Comment by kellrott** [comment]
Do you have some examples? 
What would be the preferred set of verbs for control?

**Comment by kellrott** [comment]
For the moment, GRIP isn't being used as a full database, but rather just a graph query engine. It assumes that the underlying database is responsible for MVCC and ACID.
