### ISSUE TITLE
aql/go: automatic (un)marshaling

### ISSUE THREAD

**Issue by buchanae** [bmeg/grip#40]
Most databases provide helpers for (un)marshaling Go struct types defined by the caller. In my experiments, I'm forced to marshal my struct to a string, then unmarshal to the protobuf Struct type, in order to fit the GraphElement type.

Arachne is using an ok approach (similar to what Google Datastore does), it's just missing the nice layer on top that makes it easy to work with.

**Comment by buchanae** [comment]
Related: https://godoc.org/github.com/jkawamoto/structpbconv

I may extend that package to go in reverse (interface{} -> structpb.Struct)

**Comment by adamstruck** [comment]
This functionality exists in https://github.com/bmeg/grip/blob/master/protoutil/protoutil.go
